FROM alpine

ENTRYPOINT printf '\e[93m' \
    && echo '        :::      ::::::::' \
    && echo '      :+:      :+:    :+:' \
    && echo '    +:+ +:+         +:+  ' \
    && echo '  +#+  +:+       +#+     ' \
    && echo '+#+#+#+#+#+   +#+        ' \
    && echo '     #+#    #+#          ' \
    && echo '    ###   ########       ' \
    && printf '\e[0m' && sleep 3 && exit



# docker build ex01 .
# docker run ex01